### ISSUE TITLE
Will this help?

### ISSUE THREAD

**Issue by Oogaboogaman21** [MEMEZNUT999/fluxus-key-bypasser#10]
def main():
    # ... (existing code)

    try:
        driver.get(base_url)
        time.sleep(10)  # Wait for the page to load properly
        driver.header_overrides = {'Referer': base_url}
        driver.get(f"{base_url}&7b20bcc1dfe26db966bb84f159da392f=false")
        time.sleep(5)   # Wait for the second page to load
        driver.header_overrides = {'Referer': 'https://linkvertise.com'}
        driver.get("https://fluxteam.net/windows/checkpoint/check1.php")
        time.sleep(5)   # Wait for the third page to load
        driver.get("https://fluxteam.net/windows/checkpoint/check2.php")
        time.sleep(5)   # Wait for the fourth page to load
        driver.get("https://fluxteam.net/windows/checkpoint/main.php")
        time.sleep(10)  # Wait for the final page to load

        # ... (existing code)

    except Exception as e:
        print(Fore.RED + f"An error occurred: {e}")

    finally:
        driver.quit()

if __name__ == "__main__":
    main()

**Comment by takoda121** [comment]
Setting fixed times is not a good idea you could do something like the "wait for element"
