### ISSUE TITLE
Method for bypassing without doing captcha

### ISSUE THREAD

**Issue by Simon1907** [MEMEZNUT999/fluxus-key-bypasser#2]
`    await wait(3)
    await req.request("https://flux.li/windows/start.php?HWID=" + hwid) // If you just do a request to it they already validate it, they dont even validate the captcha lol, also maybe add a feature to safe the HWID in a file but i dont know js that good + i found that out why doing my own bypass
    await wait(1)
    await req.request("https://flux.li/windows/start.php?7b20bcc1dfe26db966bb84f159da392f=false&HWID=" + hwid, {
        'Referer': start_url,
        'Cookie': commoncookie
    }) // This was the patch?? It's legit static LMAO`

Great job

We ignore the fact that i dont understand how pull requests work thats why i do it here

**Comment by Simon1907** [comment]
...
    await wait(3)
    await req.request("https://flux.li/windows/start.php?HWID=" + hwid)
    //maybe you must have these common cookies but idk
    await wait(1)
    await req.request("https://flux.li/windows/start.php?7b20bcc1dfe26db966bb84f159da392f=false&HWID=" + hwid, {
        'Referer': start_url,
        'Cookie': commoncookie
    }) // This was the patch?? It's legit static LMAO
...

**Comment by Shiawaseu** [comment]
Check this --> https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

I don't see any adjustment you added to my code. But I will consider adding a HWID saver. Thank you!

Also the cookies I just thought were significant, I am still not sure but they did have a relation to "bypassing".
