### ISSUE TITLE
In V2, why do you use Webdriver and not simple AioHttp or requests?

### ISSUE THREAD

**Issue by Simon1907** [MEMEZNUT999/fluxus-key-bypasser#4]
You did a great job, but using webdriver just slows it down a lot.

**Comment by Shiawaseu** [comment]
You can always fork this repository and adjust what you want, then create a pull request.

I am always open for ideas, thank you!

**Comment by smthpy** [comment]
I could perhaps make a fork of this and go from there, I'll see what I can do later today or tmrw.

**Comment by Shiawaseu** [comment]
Hello again,

I will be closing this “issue” due to inactivity, and also it not really an issue with the program but more of a suggestion.

If you have something to contribute, just fork this repo and create a PR after you’ve done your changes 😊
