### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by Oogaboogaman21** [MEMEZNUT999/fluxus-key-bypasser#8]
Bypassed checkpoint 2

Bypassed final checkpoint & getting key...

Your key is:

Press any key to continue . . .

It didn't say the key...

**Comment by Oogaboogaman21** [comment]
also V2 doesn't even show anything it just says 
[*] Please support me by starring the repo!
[LOG] HWID found in the file. Using that.
[!] Program is starting, if this takes longer than 1 minute, restart.

Press any key to continue . . .

**Comment by Oogaboogaman21** [comment]
> Bypassed checkpoint 2
> 
> Bypassed final checkpoint & getting key...
> 
> Your key is:
> 
> Press any key to continue . . .
> 
> It didn't say the key...

Well the V1 seems to be working but not the v2 ;-;

**Comment by MEMEZNUT999** [comment]
> also V2 doesn't even show anything it just says [*] Please support me by starring the repo! [LOG] HWID found in the file. Using that. [!] Program is starting, if this takes longer than 1 minute, restart.
> 
> Press any key to continue . . .

Happened to me too. Seems like V2 no longer works. Stick with V1.

**Comment by Oogaboogaman21** [comment]
ok

**Comment by takoda121** [comment]
> Bypassed checkpoint 2
> 
> Bypassed final checkpoint & getting key...
> 
> Your key is:
> 
> Press any key to continue . . .
> 
> It didn't say the key...
 
Would look into it but I on da vacation. 🥶 Could be mister selenium doing ungreat things.
